# Generated by Django 4.2.25 on 2025-11-11 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
