# Generated by Django 4.2.25 on 2025-11-12 11:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_employee_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organization',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
