# Generated by Django 4.2.25 on 2025-11-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_sign_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
