# Generated by Django 4.2.25 on 2025-11-13 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_sign_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='end_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
